openapi: 3.0.3
info:
  title: Catalog APIs
  version: 2.0.1
  description: Product catalog service for demo (manual-change friendly)
servers:
  - url: http://localhost:4107
paths:
  /products:
    get:
      summary: List products
      description: Returns a paginated list of products
      parameters:
        - in: query
          name: q
          schema:
            type: string
          description: Free-text search term
        - in: query
          name: limit
          schema:
            type: integer
            default: 23
          description: Page size
        - in: query
          name: offset
          schema:
            type: integer
            default: 0
          description: Offset for pagination
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Get product by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Product details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Not found
components:
  schemas:
    Product:
      type: object
      required: [id, name, price, currency]
      properties:
        id:
          type: string
          example: prod_123
        name:
          type: string
          example: Wireless Mouse
        price:
          type: number
          format: float
          example: 29.99