openapi: 3.0.3
info:
  title: Users API
  version: "1.0.0"
  description: User management API - Version 1
paths:
  /users:
    get:
      summary: List users
      description: Retrieve a paginated list of users
      parameters:
        - in: query
          name: page
          schema: 
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
      responses:
        "200":
          description: Successfully retrieved users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserV1'
                  page:
                    type: integer
                  total:
                    type: integer
              example:
                users:
                  - id: "u_1"
                    username: "alice"
                    email: "alice@example.com"
                  - id: "u_2"
                    username: "bob"
                    email: "bob@example.com"
                page: 1
                total: 2
        "400":
          description: Invalid request parameters
          content:
            application/json:
              example:
                error: "invalid_page"
                message: "Page must be a positive integer"

components:
  schemas:
    UserV1:
      type: object
      properties:
        id:
          type: string
          description: Unique user identifier
        username:
          type: string
          description: User's unique username
        email:
          type: string
          format: email
          description: User's email address
      required:
        - id
        - username
        - email
